[package]
name = "touying-simpl-uni"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Jorge Alvaro Munoz Laredo"]
license = "MIT"
description = "Touying Slide Theme for National University of Engineering"
repository = "https://github.com/jorgemunozl/touying-simpl-uni"
keywords = ["touying", "slide", "theme", "uni", "National University of Engineering"]
categories = ["presentation"]
exclude = [".github/", "examples/"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
